name: Fetch and read number
on: [push]
jobs:
  scrape_website:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: set up python
       uses: actions/setup-python@v1
       with:
         python-version: '3.9'
     - name: install tesseract-ocr
       run: |
        sudo apt install tesseract-ocr
        sudo apt install libtesseract-dev
     - name: install dependencies
       run: pip install requests opencv-python pytesseract beautifulsoup4
     - name: run scripts
       run: python reader.py 

    