name: Fetch and read number
on: 
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 7"

jobs:
  scrape_website:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: set up python
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
#     - name: install tesseract-ocr
#       run: |
#        sudo apt install tesseract-ocr
#        sudo apt install libtesseract-dev
     - name: install dependencies
       run: pip install requests beautifulsoup4 #opencv-python pytesseract 
     - name: run scripts
       run: python scrape.py
     - name: push to ntfy
       run: curl -d "$(python scrape.py)" ntfy.sh/${{ secrets.TOPIC_NAME }}
    
